; Generated by tiny16se compiler
; Source: examples/se/apu_demo.se

; Constants
LAST_FRAME_ADDR = 0x4000
SPRITE_INDEX_ADDR = 0x4002
GFX_TILES_BASE = 0x5000
GFX_OAM_BASE = 0x7800
OAM_HI = 0x78
OAM_LO = 0x00
MMIO_BASE = 0xBF00
KEYS_PRESSED_ADDR = 0xBF01
FRAME_COUNT_ADDR = 0xBF22
PPU_CTRL_ADDR = 0xBF30
APU_CTRL_ADDR = 0xBF40
APU_CH0_FREQ_LO = 0xBF42
APU_CH0_FREQ_HI = 0xBF43
APU_CH0_VOL = 0xBF44
APU_CH0_CTRL = 0xBF45
APU_CH0_ENV_AD = 0xBF51
APU_CH0_ENV_SR = 0xBF52
APU_CH0_LEN = 0xBF5B
APU_CH0_SWEEP = 0xBF5F
APU_CH1_FREQ_LO = 0xBF46
APU_CH1_FREQ_HI = 0xBF47
APU_CH1_VOL = 0xBF48
APU_CH1_CTRL = 0xBF49
APU_CH1_ENV_AD = 0xBF53
APU_CH1_ENV_SR = 0xBF54
APU_CH1_LEN = 0xBF5C
APU_CH1_SWEEP = 0xBF60
APU_CH2_FREQ_LO = 0xBF4A
APU_CH2_FREQ_HI = 0xBF4B
APU_CH2_VOL = 0xBF4C
APU_CH2_CTRL = 0xBF4D
APU_CH2_ENV_AD = 0xBF55
APU_CH2_ENV_SR = 0xBF56
APU_CH2_LEN = 0xBF5D
APU_CH3_PERIOD = 0xBF4E
APU_CH3_VOL = 0xBF4F
APU_CH3_CTRL = 0xBF50
APU_CH3_ENV_AD = 0xBF57
APU_CH3_ENV_SR = 0xBF58
APU_CH3_LEN = 0xBF5E
APU_WAVE_FREQ_LO = 0xBF61
APU_WAVE_FREQ_HI = 0xBF62
APU_WAVE_VOL = 0xBF63
APU_WAVE_CTRL = 0xBF64
APU_WAVE_ENV_AD = 0xBF59
APU_WAVE_ENV_SR = 0xBF5A
APU_WAVE_LEN = 0xBF65
APU_WAVE_RAM = 0xBF70
KEY_A = 0x04
KEY_B = 0x08
KEY_SELECT = 0x10
KEY_START = 0x20
KEY_UP = 0x40
KEY_DOWN = 0x80
KEY_LEFT = 0x01
KEY_RIGHT = 0x02
APU_DUTY_12_5 = 0x00
APU_DUTY_25 = 0x10
APU_DUTY_50 = 0x20
NOTE_C3 = 0x71A
NOTE_D3 = 0x72B
NOTE_E3 = 0x73B
NOTE_G3 = 0x75D
NOTE_A3 = 0x76C
NOTE_C4 = 0x757
NOTE_D4 = 0x767
NOTE_E4 = 0x77A
NOTE_F4 = 0x784
NOTE_G4 = 0x78F
NOTE_A4 = 0x79C
NOTE_B4 = 0x7A6
NOTE_C5 = 0x7AB
NOTE_D5 = 0x7B6
NOTE_E5 = 0x7BD
NOTE_G5 = 0x7CA
NOTE_A5 = 0x7D4

section .code

; Entry point
_start:
    CALL main
    HALT

read_frame_count:
    MOVSPR R4:R5
    LOADI R6, 0xBF
    LOADI R7, 0x22
    MOV R0, R7
    LOAD R0, [R6:R7]
    RET

wait_frame:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R6, 0x40
    LOADI R7, 0x00
    MOV R0, R7
    LOAD R0, [R6:R7]
    PUSH R0
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL read_frame_count
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R0
__L0:
    LOAD R0, [R2:R3 - 1]
    PUSH R0
    LOAD R0, [R2:R3 + 0]
    MOV R1, R0
    POP R0
    CMP R0, R1
    JZ __L2
    LOADI R0, 0
    JMP __L3
__L2:
    LOADI R0, 1
__L3:
    OR R0, R0
    JZ __L1
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL read_frame_count
    POP R5
    POP R4
    POP R3
    POP R2
    STORE R0, [R2:R3 - 1]
    JMP __L0
__L1:
    LOADI R0, 0
    LOAD R0, [R2:R3 - 1]
    PUSH R0
    LOADI R6, 0x40
    LOADI R7, 0x00
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    POP R1
    POP R1
    POP R3
    POP R2
    RET

wait_frames:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R0, 0x00
    PUSH R0
__L4:
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOAD R0, [R4:R5 + 3]
    MOV R1, R0
    POP R0
    CMP R0, R1
    JC __L6
    LOADI R0, 0
    JMP __L7
__L6:
    LOADI R0, 1
__L7:
    OR R0, R0
    JZ __L5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL wait_frame
    POP R5
    POP R4
    POP R3
    POP R2
    LOAD R0, [R2:R3 + 0]
    INC R0
    STORE R0, [R2:R3 + 0]
    JMP __L4
__L5:
    LOADI R0, 0
    POP R1
    POP R3
    POP R2
    RET

render_frame:
    MOVSPR R4:R5
    LOADI R0, 0x82
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x30
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

read_keys_pressed:
    MOVSPR R4:R5
    LOADI R6, 0xBF
    LOADI R7, 0x01
    MOV R0, R7
    LOAD R0, [R6:R7]
    RET

apu_init:
    MOVSPR R4:R5
    LOADI R0, 0x01
    PUSH R0
    LOAD R0, [R4:R5 + 3]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x40
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch0_note:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x42
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 4]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x43
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    PUSH R0
    LOAD R0, [R4:R5 + 6]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x44
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOADI R0, 0x03
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x45
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch0_env:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x51
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 6]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x52
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch0_len:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x5B
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch0_sweep:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    SHL R0
    SHL R0
    SHL R0
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOAD R0, [R4:R5 + 5]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x5F
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch0_off:
    MOVSPR R4:R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x45
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch1_note:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x46
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 4]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x47
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    PUSH R0
    LOAD R0, [R4:R5 + 6]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x48
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOADI R0, 0x03
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x49
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch1_env:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x53
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 6]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x54
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch1_len:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x5C
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch1_sweep:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    SHL R0
    SHL R0
    SHL R0
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOAD R0, [R4:R5 + 5]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x60
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch1_off:
    MOVSPR R4:R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x49
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch2_note:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x4A
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 4]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x4B
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x4C
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOADI R0, 0x03
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x4D
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch2_env:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x55
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 6]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x56
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch2_len:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x5D
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch2_off:
    MOVSPR R4:R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x4D
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch3_noise:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOAD R0, [R4:R5 + 5]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x4E
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 4]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x4F
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOADI R0, 0x03
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x50
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch3_env:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x57
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 6]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x58
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch3_len:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x5E
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

ch3_off:
    MOVSPR R4:R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x50
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

wave_note:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x61
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 4]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x62
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x63
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOADI R0, 0x03
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x64
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

wave_env:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x59
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    SHL R0
    SHL R0
    SHL R0
    SHL R0
    PUSH R0
    LOAD R0, [R4:R5 + 6]
    MOV R1, R0
    POP R0
    OR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x5A
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

wave_len:
    MOVSPR R4:R5
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x65
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

wave_write:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R0, 0x70
    PUSH R0
    LOAD R0, [R4:R5 + 3]
    MOV R1, R0
    POP R0
    ADD R0, R1
    PUSH R0
    LOADI R0, 0xBF
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    PUSH R0
    LOAD R0, [R2:R3 - 1]
    MOV R6, R0
    LOAD R0, [R2:R3 + 0]
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    POP R1
    POP R1
    POP R3
    POP R2
    RET

wave_off:
    MOVSPR R4:R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x64
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    RET

all_off:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL ch0_off
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL ch1_off
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL ch2_off
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL ch3_off
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL wave_off
    POP R5
    POP R4
    POP R3
    POP R2
    RET

toggle_ch0:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R6, 0xBF
    LOADI R7, 0x45
    MOV R0, R7
    LOAD R0, [R6:R7]
    PUSH R0
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x01
    MOV R1, R0
    POP R0
    XOR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x45
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    POP R1
    POP R3
    POP R2
    RET

toggle_ch1:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R6, 0xBF
    LOADI R7, 0x49
    MOV R0, R7
    LOAD R0, [R6:R7]
    PUSH R0
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x01
    MOV R1, R0
    POP R0
    XOR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x49
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    POP R1
    POP R3
    POP R2
    RET

toggle_ch2:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R6, 0xBF
    LOADI R7, 0x4D
    MOV R0, R7
    LOAD R0, [R6:R7]
    PUSH R0
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x01
    MOV R1, R0
    POP R0
    XOR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x4D
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    POP R1
    POP R3
    POP R2
    RET

toggle_ch3:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R6, 0xBF
    LOADI R7, 0x50
    MOV R0, R7
    LOAD R0, [R6:R7]
    PUSH R0
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x01
    MOV R1, R0
    POP R0
    XOR R0, R1
    PUSH R0
    LOADI R6, 0xBF
    LOADI R7, 0x50
    MOV R0, R7
    POP R0
    STORE R0, [R6:R7]
    POP R1
    POP R3
    POP R2
    RET

hide_all_sprites:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R0, 0x00
    PUSH R0
__L8:
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x40
    MOV R1, R0
    POP R0
    CMP R0, R1
    JC __L10
    LOADI R0, 0
    JMP __L11
__L10:
    LOADI R0, 1
__L11:
    OR R0, R0
    JZ __L9
    LOADI R0, 0x00
    PUSH R0
    LOAD R0, [R2:R3 + 0]
    SHL R0
    SHL R0
    MOV R1, R0
    POP R0
    ADD R0, R1
    PUSH R0
    LOADI R0, 0xFF
    PUSH R0
    LOADI R0, 0x78
    MOV R6, R0
    LOAD R0, [R2:R3 - 1]
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x78
    MOV R6, R0
    LOAD R0, [R2:R3 - 1]
    PUSH R0
    LOADI R0, 0x01
    MOV R1, R0
    POP R0
    ADD R0, R1
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x78
    MOV R6, R0
    LOAD R0, [R2:R3 - 1]
    PUSH R0
    LOADI R0, 0x02
    MOV R1, R0
    POP R0
    ADD R0, R1
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x78
    MOV R6, R0
    LOAD R0, [R2:R3 - 1]
    PUSH R0
    LOADI R0, 0x03
    MOV R1, R0
    POP R0
    ADD R0, R1
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    POP R1
    LOAD R0, [R2:R3 + 0]
    INC R0
    STORE R0, [R2:R3 + 0]
    JMP __L8
__L9:
    LOADI R0, 0
    POP R1
    POP R3
    POP R2
    RET

draw_char:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R0, 0x00
    PUSH R0
    LOAD R0, [R4:R5 + 6]
    SHL R0
    SHL R0
    MOV R1, R0
    POP R0
    ADD R0, R1
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    PUSH R0
    LOADI R0, 0x78
    MOV R6, R0
    LOAD R0, [R2:R3 + 0]
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOADI R0, 0x78
    MOV R6, R0
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x01
    MOV R1, R0
    POP R0
    ADD R0, R1
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    LOAD R0, [R4:R5 + 5]
    PUSH R0
    LOADI R0, 0x78
    MOV R6, R0
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x02
    MOV R1, R0
    POP R0
    ADD R0, R1
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x78
    MOV R6, R0
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x03
    MOV R1, R0
    POP R0
    ADD R0, R1
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    POP R1
    POP R3
    POP R2
    RET

draw_text:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    LOADI R0, 0x40
    MOV R6, R0
    LOADI R0, 0x02
    MOV R7, R0
    LOAD R0, [R6:R7]
    PUSH R0
    LOAD R0, [R4:R5 + 3]
    PUSH R0
    LOAD R0, [R4:R5 + 5]
    PUSH R0
    LOAD R0, [R4:R5 + 6]
    PUSH R0
__L12:
    LOAD R0, [R2:R3 - 2]
    MOV R6, R0
    LOAD R0, [R2:R3 - 3]
    MOV R7, R0
    LOAD R0, [R6:R7]
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JNZ __L14
    LOADI R0, 0
    JMP __L15
__L14:
    LOADI R0, 1
__L15:
    OR R0, R0
    JZ __L13
    LOAD R0, [R2:R3 - 2]
    MOV R6, R0
    LOAD R0, [R2:R3 - 3]
    MOV R7, R0
    LOAD R0, [R6:R7]
    PUSH R0
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOAD R0, [R2:R3 - 4]
    PUSH R0
    LOAD R0, [R4:R5 + 4]
    PUSH R0
    LOAD R0, [R2:R3 - 1]
    PUSH R0
    CALL draw_char
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    LOAD R0, [R2:R3 - 1]
    PUSH R0
    LOADI R0, 0x06
    MOV R1, R0
    POP R0
    ADD R0, R1
    STORE R0, [R2:R3 - 1]
    LOAD R0, [R2:R3 + 0]
    INC R0
    STORE R0, [R2:R3 + 0]
    LOAD R0, [R2:R3 - 3]
    INC R0
    STORE R0, [R2:R3 - 3]
    LOAD R0, [R2:R3 - 3]
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JZ __L18
    LOADI R0, 0
    JMP __L19
__L18:
    LOADI R0, 1
__L19:
    OR R0, R0
    JZ __L16
    LOAD R0, [R2:R3 - 2]
    INC R0
    STORE R0, [R2:R3 - 2]
    JMP __L17
__L16:
    LOADI R0, 0x00
__L17:
    POP R1
    JMP __L12
__L13:
    LOADI R0, 0
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x40
    MOV R6, R0
    LOADI R0, 0x02
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    POP R1
    POP R1
    POP R1
    POP R1
    POP R3
    POP R2
    RET

init_text_display:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL hide_all_sprites
    POP R5
    POP R4
    POP R3
    POP R2
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x40
    MOV R6, R0
    LOADI R0, 0x02
    MOV R7, R0
    POP R0
    STORE R0, [R6:R7]
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x03
    PUSH R0
    LOADI R0, 0x40
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL draw_text
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0E
    PUSH R0
    LOADI R0, 0x40
    PUSH R0
    LOADI R0, 0x0A
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL draw_text
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x15
    PUSH R0
    LOADI R0, 0x40
    PUSH R0
    LOADI R0, 0x12
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL draw_text
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x1D
    PUSH R0
    LOADI R0, 0x40
    PUSH R0
    LOADI R0, 0x1A
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL draw_text
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x25
    PUSH R0
    LOADI R0, 0x40
    PUSH R0
    LOADI R0, 0x26
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL draw_text
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x2D
    PUSH R0
    LOADI R0, 0x40
    PUSH R0
    LOADI R0, 0x2E
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL draw_text
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x35
    PUSH R0
    LOADI R0, 0x40
    PUSH R0
    LOADI R0, 0x36
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL draw_text
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x3C
    PUSH R0
    LOADI R0, 0x40
    PUSH R0
    LOADI R0, 0x3E
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL draw_text
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL render_frame
    POP R5
    POP R4
    POP R3
    POP R2
    RET

setup_wave_ram:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x00
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x02
    PUSH R0
    LOADI R0, 0x01
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x03
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x08
    PUSH R0
    LOADI R0, 0x04
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0A
    PUSH R0
    LOADI R0, 0x05
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x06
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0E
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0F
    PUSH R0
    LOADI R0, 0x08
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0E
    PUSH R0
    LOADI R0, 0x09
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x0A
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0A
    PUSH R0
    LOADI R0, 0x0B
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x08
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x0D
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x0E
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x02
    PUSH R0
    LOADI R0, 0x0F
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x01
    PUSH R0
    LOADI R0, 0x10
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x03
    PUSH R0
    LOADI R0, 0x11
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x05
    PUSH R0
    LOADI R0, 0x12
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x13
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x14
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0B
    PUSH R0
    LOADI R0, 0x15
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0D
    PUSH R0
    LOADI R0, 0x16
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0F
    PUSH R0
    LOADI R0, 0x17
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0D
    PUSH R0
    LOADI R0, 0x18
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0B
    PUSH R0
    LOADI R0, 0x19
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x1A
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x1B
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x05
    PUSH R0
    LOADI R0, 0x1C
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x03
    PUSH R0
    LOADI R0, 0x1D
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x01
    PUSH R0
    LOADI R0, 0x1E
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x1F
    PUSH R0
    CALL wave_write
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    RET

play_timing_melody:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xAB
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x7A
    PUSH R0
    CALL ch1_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x1A
    PUSH R0
    CALL ch2_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x57
    PUSH R0
    CALL wave_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x02
    PUSH R0
    CALL ch3_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x06
    PUSH R0
    CALL ch3_noise
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xB6
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x84
    PUSH R0
    CALL ch1_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x2B
    PUSH R0
    CALL ch2_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x67
    PUSH R0
    CALL wave_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xBD
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x8F
    PUSH R0
    CALL ch1_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x3B
    PUSH R0
    CALL ch2_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x7A
    PUSH R0
    CALL wave_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x02
    PUSH R0
    CALL ch3_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x06
    PUSH R0
    CALL ch3_noise
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xCA
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xA6
    PUSH R0
    CALL ch1_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x5D
    PUSH R0
    CALL ch2_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x8F
    PUSH R0
    CALL wave_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xD4
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xAB
    PUSH R0
    CALL ch1_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x6C
    PUSH R0
    CALL ch2_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x9C
    PUSH R0
    CALL wave_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x02
    PUSH R0
    CALL ch3_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x06
    PUSH R0
    CALL ch3_noise
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xCA
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xA6
    PUSH R0
    CALL ch1_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x5D
    PUSH R0
    CALL ch2_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x8F
    PUSH R0
    CALL wave_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xBD
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x8F
    PUSH R0
    CALL ch1_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x3B
    PUSH R0
    CALL ch2_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x7A
    PUSH R0
    CALL wave_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x02
    PUSH R0
    CALL ch3_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x06
    PUSH R0
    CALL ch3_noise
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xB6
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x09
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x84
    PUSH R0
    CALL ch1_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x2B
    PUSH R0
    CALL ch2_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x67
    PUSH R0
    CALL wave_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    RET

play_timing_test:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x0A
    PUSH R0
    LOADI R0, 0x03
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL ch0_env
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x05
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x03
    PUSH R0
    LOADI R0, 0x01
    PUSH R0
    CALL ch1_env
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x01
    PUSH R0
    CALL ch2_env
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x03
    PUSH R0
    LOADI R0, 0x00
    PUSH R0
    CALL ch3_env
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x0A
    PUSH R0
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    CALL wave_env
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL setup_wave_ram
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL ch0_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL ch1_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL ch2_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wave_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x02
    PUSH R0
    CALL ch3_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x02
    PUSH R0
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x03
    PUSH R0
    CALL ch0_sweep
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x01
    PUSH R0
    LOADI R0, 0x01
    PUSH R0
    LOADI R0, 0x04
    PUSH R0
    CALL ch1_sweep
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL play_timing_melody
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x78
    PUSH R0
    CALL ch0_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x78
    PUSH R0
    CALL ch1_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x78
    PUSH R0
    CALL ch2_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x78
    PUSH R0
    CALL wave_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x20
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xAB
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0A
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x8F
    PUSH R0
    CALL ch1_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x1A
    PUSH R0
    CALL ch2_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0x57
    PUSH R0
    CALL wave_note
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x78
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL all_off
    POP R5
    POP R4
    POP R3
    POP R2
    RET

play_explosion:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x01
    PUSH R0
    CALL ch3_env
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x0F
    PUSH R0
    LOADI R0, 0x08
    PUSH R0
    CALL ch3_noise
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x12
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL ch3_off
    POP R5
    POP R4
    POP R3
    POP R2
    RET

play_coin:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x03
    PUSH R0
    LOADI R0, 0x08
    PUSH R0
    LOADI R0, 0x02
    PUSH R0
    LOADI R0, 0x01
    PUSH R0
    CALL ch0_env
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x04
    PUSH R0
    CALL ch0_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xA6
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x03
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL ch0_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x10
    PUSH R0
    LOADI R0, 0x0C
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xBD
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL ch0_off
    POP R5
    POP R4
    POP R3
    POP R2
    RET

play_jump:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x06
    PUSH R0
    LOADI R0, 0x04
    PUSH R0
    LOADI R0, 0x01
    PUSH R0
    CALL ch0_env
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x02
    PUSH R0
    LOADI R0, 0x01
    PUSH R0
    LOADI R0, 0x04
    PUSH R0
    CALL ch0_sweep
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0C
    PUSH R0
    CALL ch0_len
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x00
    PUSH R0
    LOADI R0, 0x0A
    PUSH R0
    LOADI R0, 0x07
    PUSH R0
    LOADI R0, 0xAB
    PUSH R0
    CALL ch0_note
    POP R1
    POP R1
    POP R1
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x0C
    PUSH R0
    CALL wait_frames
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL ch0_off
    POP R5
    POP R4
    POP R3
    POP R2
    RET

handle_input:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    MOVSPR R2:R3
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL read_keys_pressed
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R0
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x04
    MOV R1, R0
    POP R0
    AND R0, R1
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JNZ __L22
    LOADI R0, 0
    JMP __L23
__L22:
    LOADI R0, 1
__L23:
    OR R0, R0
    JZ __L20
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL play_timing_test
    POP R5
    POP R4
    POP R3
    POP R2
    JMP __L21
__L20:
    LOADI R0, 0x00
__L21:
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x08
    MOV R1, R0
    POP R0
    AND R0, R1
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JNZ __L26
    LOADI R0, 0
    JMP __L27
__L26:
    LOADI R0, 1
__L27:
    OR R0, R0
    JZ __L24
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL play_explosion
    POP R5
    POP R4
    POP R3
    POP R2
    JMP __L25
__L24:
    LOADI R0, 0x00
__L25:
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x40
    MOV R1, R0
    POP R0
    AND R0, R1
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JNZ __L30
    LOADI R0, 0
    JMP __L31
__L30:
    LOADI R0, 1
__L31:
    OR R0, R0
    JZ __L28
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL play_coin
    POP R5
    POP R4
    POP R3
    POP R2
    JMP __L29
__L28:
    LOADI R0, 0x00
__L29:
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x80
    MOV R1, R0
    POP R0
    AND R0, R1
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JNZ __L34
    LOADI R0, 0
    JMP __L35
__L34:
    LOADI R0, 1
__L35:
    OR R0, R0
    JZ __L32
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL play_jump
    POP R5
    POP R4
    POP R3
    POP R2
    JMP __L33
__L32:
    LOADI R0, 0x00
__L33:
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x10
    MOV R1, R0
    POP R0
    AND R0, R1
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JNZ __L38
    LOADI R0, 0
    JMP __L39
__L38:
    LOADI R0, 1
__L39:
    OR R0, R0
    JZ __L36
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL toggle_ch0
    POP R5
    POP R4
    POP R3
    POP R2
    JMP __L37
__L36:
    LOADI R0, 0x00
__L37:
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x20
    MOV R1, R0
    POP R0
    AND R0, R1
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JNZ __L42
    LOADI R0, 0
    JMP __L43
__L42:
    LOADI R0, 1
__L43:
    OR R0, R0
    JZ __L40
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL toggle_ch1
    POP R5
    POP R4
    POP R3
    POP R2
    JMP __L41
__L40:
    LOADI R0, 0x00
__L41:
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x01
    MOV R1, R0
    POP R0
    AND R0, R1
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JNZ __L46
    LOADI R0, 0
    JMP __L47
__L46:
    LOADI R0, 1
__L47:
    OR R0, R0
    JZ __L44
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL toggle_ch2
    POP R5
    POP R4
    POP R3
    POP R2
    JMP __L45
__L44:
    LOADI R0, 0x00
__L45:
    LOAD R0, [R2:R3 + 0]
    PUSH R0
    LOADI R0, 0x02
    MOV R1, R0
    POP R0
    AND R0, R1
    PUSH R0
    LOADI R0, 0x00
    MOV R1, R0
    POP R0
    CMP R0, R1
    JNZ __L50
    LOADI R0, 0
    JMP __L51
__L50:
    LOADI R0, 1
__L51:
    OR R0, R0
    JZ __L48
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL toggle_ch3
    POP R5
    POP R4
    POP R3
    POP R2
    JMP __L49
__L48:
    LOADI R0, 0x00
__L49:
    POP R1
    POP R3
    POP R2
    RET

main:
    MOVSPR R4:R5
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    LOADI R0, 0x08
    PUSH R0
    CALL apu_init
    POP R1
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL init_text_display
    POP R5
    POP R4
    POP R3
    POP R2
__L52:
    LOADI R0, 0x01
    OR R0, R0
    JZ __L53
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL wait_frame
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL handle_input
    POP R5
    POP R4
    POP R3
    POP R2
    PUSH R2
    PUSH R3
    PUSH R4
    PUSH R5
    CALL render_frame
    POP R5
    POP R4
    POP R3
    POP R2
    JMP __L52
__L53:
    LOADI R0, 0
    RET

section .data

    ORG 0x4000
user_data:
    DB 0x00
    DB 0x00
    DB 0x00

    ORG 0x4003
text_line1:
    DB 0x41, 0x20, 0x54, 0x49, 0x4D, 0x49, 0x4E, 0x47, 0x20, 0x50
    DB 0x00

    ORG 0x400E
text_line2:
    DB 0x42, 0x20, 0x42, 0x4F, 0x4F, 0x4D
    DB 0x00

    ORG 0x4015
text_line3:
    DB 0x55, 0x50, 0x20, 0x43, 0x4F, 0x49, 0x4E
    DB 0x00

    ORG 0x401D
text_line4:
    DB 0x44, 0x4E, 0x20, 0x4A, 0x55, 0x4D, 0x50
    DB 0x00

    ORG 0x4025
text_line5:
    DB 0x53, 0x45, 0x4C, 0x20, 0x43, 0x48, 0x30
    DB 0x00

    ORG 0x402D
text_line6:
    DB 0x53, 0x54, 0x41, 0x20, 0x43, 0x48, 0x31
    DB 0x00

    ORG 0x4035
text_line7:
    DB 0x4C, 0x54, 0x20, 0x54, 0x52, 0x49
    DB 0x00

    ORG 0x403C
text_line8:
    DB 0x52, 0x54, 0x20, 0x4E, 0x4F, 0x49, 0x53, 0x45
    DB 0x00

.include "../includes/font.inc"
