#include <ctype.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#define REQUIRED_ARGS                                                                              \
    REQUIRED_STRING_ARG(input_png, "input", "PNG image file (8x8 tiles)")                          \
    REQUIRED_STRING_ARG(output_inc, "output", "Output assembly file (.inc)")

#define OPTIONAL_ARGS                                                                              \
    OPTIONAL_STRING_ARG(name, "", "-n", "name", "Symbol name (default: from filename)")

#define BOOLEAN_ARGS BOOLEAN_ARG(help, "-h", "Show help")

#include "easyargs.h"
#include "ppu.h"

args_t args;

typedef struct {
    uint8_t r, g, b, a;
} RGBA;

uint8_t rgba_to_rgb332(RGBA color) {
    uint8_t r = (color.r >> 5) & 0x07; // 3 bits
    uint8_t g = (color.g >> 5) & 0x07; // 3 bits
    uint8_t b = (color.b >> 6) & 0x03; // 2 bits
    return (r << 5) | (g << 2) | b;
}

bool colors_match(RGBA a, RGBA b) {
    // Consider transparent pixels as matching
    if (a.a < 128 && b.a < 128) return true;

    // For opaque pixels, compare RGB values with small tolerance
    if (a.a >= 128 && b.a >= 128) {
        int dr = abs((int)a.r - (int)b.r);
        int dg = abs((int)a.g - (int)b.g);
        int db = abs((int)a.b - (int)b.b);
        return (dr + dg + db) < 10;
    }

    return false;
}

typedef struct {
    RGBA colors[256];
    int count;
} Palette;

void palette_init(Palette* pal) {
    memset(pal, 0, sizeof(Palette));
    pal->count = 0;
}

void palette_from_image(Palette* pal, uint8_t* image, int width, int height) {
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            int pixel_index = (y * width + x) * 4;
            RGBA color = {.r = image[pixel_index + 0],
                          .g = image[pixel_index + 1],
                          .b = image[pixel_index + 2],
                          .a = image[pixel_index + 3]};

            if (color.a < 128) continue;

            bool found = false;
            for (int i = 0; i < pal->count; i++) {
                if (colors_match(pal->colors[i], color)) {
                    found = true;
                    break;
                }
            }

            if (!found) {
                if (pal->count >= 256) {
                    fprintf(stderr, "Error: Image has too many unique colors (max 256)\n");
                    return;
                }
                pal->colors[pal->count++] = color;
            }
        }
    }
}

int palette_find_color(Palette* pal, RGBA color) {
    if (color.a < 128) return 0;
    for (int i = 0; i < pal->count; i++) {
        if (colors_match(pal->colors[i], color)) return i;
    }
    fprintf(stderr, "Warning: Color not found in palette\n");
    return 0;
}

typedef struct {
    uint8_t data[32]; // 8x8 pixels, 4 bits per pixel (2 pixels per byte)
} Tile;

void extract_tile(uint8_t* image, int image_width, int image_height, int tile_x, int tile_y,
                  Palette* pal, Tile* tile) {
    memset(tile, 0, sizeof(Tile));

    for (int y = 0; y < TINY16_TILE_HEIGHT; y++) {
        for (int x = 0; x < TINY16_TILE_WIDTH; x++) {
            int pixel_x = tile_x * TINY16_TILE_WIDTH + x;
            int pixel_y = tile_y * TINY16_TILE_HEIGHT + y;

            if (pixel_x >= image_width || pixel_y >= image_height) {
                continue;
            }

            int pixel_index = (pixel_y * image_width + pixel_x) * 4;
            RGBA color = {.r = image[pixel_index + 0],
                          .g = image[pixel_index + 1],
                          .b = image[pixel_index + 2],
                          .a = image[pixel_index + 3]};

            uint8_t palette_index = palette_find_color(pal, color);

            // 4bpp: pack 2 pixels per byte
            // Even pixels (0,2,4,6) go in high nibble, odd pixels (1,3,5,7) go in low nibble
            int byte_index = y * 4 + (x / 2);
            if (x & 1) {
                // Odd pixel: low nibble
                tile->data[byte_index] |= (palette_index & 0x0F);
            } else {
                // Even pixel: high nibble
                tile->data[byte_index] |= (palette_index & 0x0F) << 4;
            }
        }
    }
}

void output_asm_include(FILE* f, Tile* tiles, int tile_count, Palette* pal, const char* name) {
    fprintf(f, "; vim: set ft=asm:\n");
    fprintf(f, "; generated by png2tiles\n\n");

    // Tiles first (lower address)
    fprintf(f, "; tiles (%d total, 32 bytes each, 4bpp)\n", tile_count);
    fprintf(f, "ORG 0x5000\n");
    fprintf(f, "%s_tiles:\n", name);
    for (int t = 0; t < tile_count; t++) {
        fprintf(f, "; tile %d\n", t);
        for (int i = 0; i < 32; i += 8) {
            fprintf(f, "    DB ");
            int bytes_to_print = (i + 8 <= 32) ? 8 : (32 - i);
            for (int j = 0; j < bytes_to_print; j++) {
                fprintf(f, "0x%02X", tiles[t].data[i + j]);
                if (j < bytes_to_print - 1) fprintf(f, ", ");
            }
            fprintf(f, "\n");
        }
    }
    fprintf(f, "\n");

    // Palette second (higher address)
    fprintf(f, "; palette (%d colors, max 16 for 4bpp)\n", pal->count);
    fprintf(f, "ORG 0x7900\n");
    fprintf(f, "%s_palette:\n", name);
    for (int i = 0; i < 16; i++) {
        if (i < pal->count) {
            uint8_t rgb332 = rgba_to_rgb332(pal->colors[i]);
            fprintf(f, "    DB 0x%02X  ; Color %d: RGB(%d,%d,%d)\n", rgb332, i, pal->colors[i].r,
                    pal->colors[i].g, pal->colors[i].b);
        } else {
            fprintf(f, "    DB 0x00  ; Unused\n");
        }
    }
}

int main(int argc, char** argv) {
    args = make_default_args();
    if (!parse_args(argc, argv, &args) || args.help) {
        print_help(argv[0]);
        printf("\nConverts PNG images to Tiny16 assembly tile data.\n");
        printf("Format: 4bpp palette mode (16 colors, 255 tiles, 32 bytes/tile)\n");
        return args.help ? 0 : 1;
    }

    const char* input_file = args.input_png;
    const char* output_file = args.output_inc;
    const char* symbol_name = args.name;

    // extract symbol name from filename if not provided
    char auto_name[256] = {0};
    if (!symbol_name || symbol_name[0] == '\0') {
        const char* basename = strrchr(input_file, '/');
        basename = basename ? basename + 1 : input_file;
        strncpy(auto_name, basename, sizeof(auto_name) - 1);

        char* dot = strrchr(auto_name, '.');
        if (dot) *dot = '\0';

        for (char* p = auto_name; *p; p++) {
            if (!isalnum(*p)) *p = '_';
        }

        symbol_name = auto_name;
    }

    // load png
    int width, height, channels;
    uint8_t* image = stbi_load(input_file, &width, &height, &channels, 4);

    if (!image) {
        fprintf(stderr, "Error: Failed to load '%s'\n", input_file);
        return 1;
    }

    printf("Loaded %s: %dx%d, %d channels\n", input_file, width, height, channels);

    // validate dimensions
    if (width % TINY16_TILE_WIDTH != 0 || height % TINY16_TILE_HEIGHT != 0) {
        fprintf(stderr,
                "Warning: Image dimensions (%dx%d) are not multiples of tile size (%dx%d)\n", width,
                height, TINY16_TILE_WIDTH, TINY16_TILE_HEIGHT);
    }

    // extract tiles
    int tiles_x = width / TINY16_TILE_WIDTH;
    int tiles_y = height / TINY16_TILE_HEIGHT;
    int tile_count = tiles_x * tiles_y;

    if (tile_count > 255) {
        fprintf(stderr, "Warning: Image contains %d tiles, max 255 supported\n", tile_count);
        tile_count = 255;
    }

    // extract palette from entire image
    Palette palette;
    palette_init(&palette);

    printf("Analyzing image colors...\n");
    palette_from_image(&palette, image, width, height);

    if (palette.count > 16) {
        fprintf(stderr, "Error: Image has %d colors (max 16 for 4bpp)\n", palette.count);
        fprintf(stderr, "Hint: Use 'magick input.png -colors 16 output.png' to reduce colors\n");
        stbi_image_free(image);
        return 1;
    }

    printf("Found %d unique colors (4bpp mode)\n", palette.count);
    printf("Extracting %d tiles (%dx%d grid)...\n", tile_count, tiles_x, tiles_y);

    Tile* tiles = calloc(tile_count, sizeof(Tile));
    if (!tiles) {
        fprintf(stderr, "Error: Out of memory\n");
        stbi_image_free(image);
        return 1;
    }

    int tile_index = 0;
    for (int ty = 0; ty < tiles_y && tile_index < tile_count; ty++) {
        for (int tx = 0; tx < tiles_x && tile_index < tile_count; tx++) {
            extract_tile(image, width, height, tx, ty, &palette, &tiles[tile_index++]);
        }
    }

    // write output (assembly format)
    FILE* out = fopen(output_file, "w");
    if (!out) {
        fprintf(stderr, "Error: Failed to open '%s' for writing\n", output_file);
        free(tiles);
        stbi_image_free(image);
        return 1;
    }

    output_asm_include(out, tiles, tile_count, &palette, symbol_name);

    fclose(out);
    free(tiles);
    stbi_image_free(image);

    printf("Wrote %s (32 bytes/tile, %d tiles, %d colors)\n", output_file, tile_count,
           palette.count);

    return 0;
}
